"""Deterministic Japanese-to-English prompt compiler for MiniMax-H3.

The language model only receives independent translatable leaves. H3 control
tags, dialogue, subtitle literals, whitespace, and structural separators never
leave this module and are reassembled in their original order.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
import re
from typing import Mapping


class PromptCompileError(ValueError):
    """Raised when a translation cannot be accepted without changing structure."""


@dataclass(frozen=True)
class TranslationFragment:
    id: str
    text: str


@dataclass(frozen=True)
class _Piece:
    text: str
    translation_id: str | None = None


@dataclass(frozen=True)
class TranslationPlan:
    source: str
    pieces: tuple[_Piece, ...]
    fragments: tuple[TranslationFragment, ...]


_JAPANESE_RE = re.compile(r"[\u3040-\u30ff\u3400-\u9fff\uff66-\uff9f]")
_SHIRONA_RE = re.compile(r"しろな|シロナ")

# Order matters: an entire dialogue block must win over the generic angle-tag
# alternative. Japanese strings duplicated for subtitles are protected too.
_IMMUTABLE_RE = re.compile(
    r"<d(?:\s[^<>]*)?>.*?</d>"
    r"|「[^」]*」"
    r"|\"[^\"\r\n]*[\u3040-\u30ff\u3400-\u9fff\uff66-\uff9f][^\"\r\n]*\""
    r"|“[^”\r\n]*[\u3040-\u30ff\u3400-\u9fff\uff66-\uff9f][^”\r\n]*”"
    r"|<[^<>\r\n]+>",
    flags=re.DOTALL | re.IGNORECASE,
)

# These delimiters define the H3 prompt layout. They are serialized by code,
# never generated by the LLM. Japanese sentence marks stay with their leaf so
# the translation can replace them with natural English punctuation.
_STRUCTURE_RE = re.compile(r"(\r\n|\r|\n|[:：→])")
_JAPANESE_SENTENCE_RE = re.compile(r"(?<=[。！？；])")
_FORBIDDEN_TRANSLATION_RE = re.compile(r"[\r\n<>:：→]")


def _split_whitespace(value: str) -> tuple[str, str, str]:
    if not value.strip():
        return value, "", ""
    prefix_match = re.match(r"\s*", value)
    suffix_match = re.search(r"\s*$", value)
    prefix = prefix_match.group(0) if prefix_match else ""
    suffix = suffix_match.group(0) if suffix_match else ""
    end = len(value) - len(suffix) if suffix else len(value)
    return prefix, value[len(prefix):end], suffix


def _append_leaf(pieces: list[_Piece], fragments: list[TranslationFragment], value: str) -> None:
    if not value:
        return
    prefix, core, suffix = _split_whitespace(value)
    if prefix:
        pieces.append(_Piece(prefix))
    if core:
        normalized = _SHIRONA_RE.sub("Shirona", core)
        if _JAPANESE_RE.search(normalized):
            fragment_id = f"T{len(fragments):04d}"
            fragments.append(TranslationFragment(fragment_id, normalized))
            pieces.append(_Piece(core, fragment_id))
        else:
            # Proper-name replacement is deterministic and needs no LLM call.
            pieces.append(_Piece(normalized))
    if suffix:
        pieces.append(_Piece(suffix))


def _append_translatable_region(
    pieces: list[_Piece], fragments: list[TranslationFragment], value: str
) -> None:
    for structural_part in _STRUCTURE_RE.split(value):
        if not structural_part:
            continue
        if _STRUCTURE_RE.fullmatch(structural_part):
            pieces.append(_Piece(structural_part))
            continue
        sentences = _JAPANESE_SENTENCE_RE.split(structural_part)
        for index, sentence in enumerate(sentences):
            _append_leaf(pieces, fragments, sentence)
            # Japanese prose normally has no space after 。！？；. Once each
            # sentence is translated independently, insert the English word
            # boundary deterministically instead of asking the LLM to infer it.
            if (
                index + 1 < len(sentences)
                and sentence.endswith(("。", "！", "？", "；"))
                and sentences[index + 1]
                and not sentences[index + 1][0].isspace()
            ):
                pieces.append(_Piece(" "))


def build_translation_plan(source: str) -> TranslationPlan:
    """Compile source into immutable structure and independent translation leaves."""
    if not isinstance(source, str) or not source.strip():
        raise PromptCompileError("翻訳するプロンプトを入力してください")

    pieces: list[_Piece] = []
    fragments: list[TranslationFragment] = []
    cursor = 0
    for match in _IMMUTABLE_RE.finditer(source):
        _append_translatable_region(pieces, fragments, source[cursor:match.start()])
        pieces.append(_Piece(match.group(0)))
        cursor = match.end()
    _append_translatable_region(pieces, fragments, source[cursor:])
    return TranslationPlan(source, tuple(pieces), tuple(fragments))


def _protected_spans(value: str) -> tuple[str, ...]:
    return tuple(match.group(0) for match in _IMMUTABLE_RE.finditer(value))


def _structure_signature(value: str) -> tuple[str, ...]:
    return tuple(match.group(0) for match in _STRUCTURE_RE.finditer(value))


def render_translation(plan: TranslationPlan, translations: Mapping[str, str]) -> str:
    """Reassemble a translated prompt, rejecting any structural mutation."""
    expected_ids = {fragment.id for fragment in plan.fragments}
    actual_ids = set(translations)
    if actual_ids != expected_ids:
        missing = sorted(expected_ids - actual_ids)
        extra = sorted(actual_ids - expected_ids)
        detail = []
        if missing:
            detail.append("不足=" + ",".join(missing))
        if extra:
            detail.append("余分=" + ",".join(extra))
        raise PromptCompileError("Ollamaの翻訳項目IDが一致しません（" + " / ".join(detail) + "）")

    accepted: dict[str, str] = {}
    for fragment in plan.fragments:
        translated = translations[fragment.id]
        if not isinstance(translated, str):
            raise PromptCompileError(f"{fragment.id} の翻訳結果が文字列ではありません")
        translated = translated.strip()
        if not translated:
            raise PromptCompileError(f"{fragment.id} の翻訳結果が空です")
        if _JAPANESE_RE.search(translated):
            raise PromptCompileError(f"{fragment.id} に未翻訳の日本語が残っています")
        if _FORBIDDEN_TRANSLATION_RE.search(translated):
            raise PromptCompileError(f"{fragment.id} がH3の構造記号を生成しました")
        accepted[fragment.id] = translated

    output = "".join(
        accepted[piece.translation_id] if piece.translation_id else piece.text
        for piece in plan.pieces
    )
    if _protected_spans(output) != _protected_spans(plan.source):
        raise PromptCompileError("台詞・字幕または参照タグの完全一致検証に失敗しました")
    if _structure_signature(output) != _structure_signature(plan.source):
        raise PromptCompileError("シーン・ショット・カメラ・音の構造検証に失敗しました")
    return output


def parse_translation_response(content: str) -> dict[str, str]:
    """Parse the deliberately narrow JSON contract used with Ollama."""
    cleaned = re.sub(r"<think>.*?</think>", "", content, flags=re.DOTALL).strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*|\s*```$", "", cleaned, flags=re.IGNORECASE)
    try:
        payload = json.loads(cleaned)
    except json.JSONDecodeError as exc:
        raise PromptCompileError("Ollamaが有効な翻訳JSONを返しませんでした") from exc
    rows = payload.get("translations") if isinstance(payload, dict) else None
    if not isinstance(rows, list):
        raise PromptCompileError("Ollamaの翻訳JSONにtranslations配列がありません")
    translations: dict[str, str] = {}
    for row in rows:
        if not isinstance(row, dict) or not isinstance(row.get("id"), str):
            raise PromptCompileError("Ollamaの翻訳項目が不正です")
        fragment_id = row["id"]
        if fragment_id in translations:
            raise PromptCompileError(f"Ollamaが{fragment_id}を重複して返しました")
        text = row.get("text")
        if not isinstance(text, str):
            raise PromptCompileError(f"Ollamaの{fragment_id}が文字列ではありません")
        translations[fragment_id] = text
    return translations
